name: Go

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
        
    - name: Set up Tensorflow c Library
      run: |
        wget https://storage.googleapis.com/clitelibrary/ctflitelib_2.4.0.tar.gz
        sudo tar -C /usr/local -xzf ctflitelib_2.4.0.tar.gz
        sudo ldconfig
        sudo apt-get update
        sudo apt-get install gcc

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: gotflite
      uses: actions/checkout@v2
  
    - name: Build
      run: go build .

    - name: Test
      run: go test -v
